name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Build and Deploy
      uses: solybum/hexo-deploy@master
      env:
        PERSONAL_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
        PUBLISH_REPOSITORY: ackerr/Ackerr.github.io
        BRANCH: master
        PUBLISH_DIR: ./public # The folder the action should deploy.
